# Generated by Django 3.2.6 on 2021-08-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('company_website', models.CharField(max_length=70)),
                ('fax_number', models.CharField(max_length=70)),
                ('street', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company_images')),
                ('template', models.PositiveSmallIntegerField(choices=[(0, 'default'), (1, 'select1')], default=0)),
                ('stripe_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company',
                'ordering': ('-pk',),
            },
        ),
    ]
